### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by codeowl1** [anseki/gulp-pre-proc#1]
Hi there,

Thanks for your work on gulp-pre-proc!

I am wanting to create a gulp task that will extract a javascript element from a html page and once I have the element html I can parse it to extract a comma delimited array of file names from the query string in the src attribute, and then minify and concatenate these files.

The HTML looks like this:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <!-- [BUNDLE_JS] -->
    <script type="text/javascript" src="/processedjs/?
b=js
&f=
MISTRO/Modules/Generic/Grid.js,
MISTRO/Modules/Generic/Toolbar.js,
MISTRO/PageControllers/UserManagement.js
&debug=true
"></script>
    <!-- [/BUNDLE_JS] -->
</head>
...
```

The gulpfile.js looks like this:

```
var gulp = require('gulp'),
    debug = require('gulp-debug'),
    through2 = require('through2'),
    pre_proc = require('gulp-pre-proc')
;

gulp.task('test', function () {
    return gulp.src(['./dev/*.html'])
        .pipe(debug())
        .pipe(pre_proc({
            pickTag: { tag: 'BUNDLE_JS' }
        }))
        //.pipe(through2.obj(function (chunk, enc, callback) {
        //    // The chunk comes through as a vinyl object https://github.com/wearefractal/vinyl
        //    console.log(chunk.toString(enc));
        //}))
    ;
});

gulp.task('default', ['test']);
```

When I run it I get the following error.  If I comment out the following code I do not get the error:

```
.pipe(pre_proc({
    pickTag: { tag: 'BUNDLE_JS' }
}))
```

What am I doing wrong?

Is gulp-pre-proc.pickTag suited to what I am trying to do?  Or should I look into writing my own plugin?

c:\Source\GULPTestBed\GULPTestBed>gulp
[22:06:30] Using gulpfile c:\Source\GULPTestBed\GULPTestBed\gulpfile.js
[22:06:30] Starting 'test'...
[22:06:30] gulp-debug: dev\Test1.html
buffer.js:179
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at DestroyableTransform._transform (c:\Source\GULPTestBed\GULPTestBed\node_modules\gulp-pre-proc\index.js:40:64)
    at DestroyableTransform.Transform._read (c:\Source\GULPTestBed\GULPTestBed\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (c:\Source\GULPTestBed\GULPTestBed\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (c:\Source\GULPTestBed\GULPTestBed\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (c:\Source\GULPTestBed\GULPTestBed\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (c:\Source\GULPTestBed\GULPTestBed\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (c:\Source\GULPTestBed\GULPTestBed\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:115:13)
    at DestroyableTransform.emit (events.js:210:7)

**Comment by anseki** [comment]
Hi @codeowl1, thank you for the comment.

I tried your code, then that worked perfectly without error. And just only the `<script>` element was output.
So, was that error thrown by the code you showed?
Also, your Node.js or Gulp might be broken (e.g. version inconsistency). It might be solved by re-setup Gulp.

**Comment by codeowl1** [comment]
@anseki, Thanks for the prompt response, much appreciated!

I am running the script on:
OS: Windows 10
NodeJS: 8.4.0
Gulp: CLI version 3.9.1
Gulp: Local version 3.9.1

I just re-ran the test in a new directory as follows:

1) Created dir: C:\Source\GULPTestBed\GulpNewTest
2) Copied gulpfile.js and dev dir from previous test into above dir.
3) Open cmd prompt and cd to C:\Source\GULPTestBed\GulpNewTest.
4) Installed gulp global: 
```
C:\Source\GULPTestBed\GulpNewTest>npm install gulp -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
C:\Users\[USERNAME]\AppData\Roaming\npm\gulp -> C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
+ gulp@3.9.1
updated 1 package in 11.083s
```
5) Installed gulp local:
```
C:\Source\GULPTestBed\GulpNewTest>npm install gulp --save-dev
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN saveError ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN GulpNewTest No description
npm WARN GulpNewTest No repository field.
npm WARN GulpNewTest No README data
npm WARN GulpNewTest No license field.

+ gulp@3.9.1
added 270 packages in 13.784s
```

6) Installed gulp-debug:
```
C:\Source\GULPTestBed\GulpNewTest>npm install gulp-debug --save-dev
npm WARN saveError ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN GulpNewTest No description
npm WARN GulpNewTest No repository field.
npm WARN GulpNewTest No README data
npm WARN GulpNewTest No license field.

+ gulp-debug@3.2.0
added 13 packages in 5.541s
```

7) Installed through2:
```
C:\Source\GULPTestBed\GulpNewTest>npm install through2 --save-dev
npm WARN saveError ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN GulpNewTest No description
npm WARN GulpNewTest No repository field.
npm WARN GulpNewTest No README data
npm WARN GulpNewTest No license field.

+ through2@2.0.3
updated 1 package in 4.101s
```

8) Installed gulp-pre-proc:
```
C:\Source\GULPTestBed\GulpNewTest>npm install gulp-pre-proc --save-dev
npm WARN saveError ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Source\GULPTestBed\GulpNewTest\package.json'
npm WARN GulpNewTest No description
npm WARN GulpNewTest No repository field.
npm WARN GulpNewTest No README data
npm WARN GulpNewTest No license field.

+ gulp-pre-proc@1.0.6
added 4 packages in 4.708s
```

9) Ran gulp:
```
C:\Source\GULPTestBed\GulpNewTest>gulp
[09:26:03] Using gulpfile C:\Source\GULPTestBed\GulpNewTest\gulpfile.js
[09:26:03] Starting 'test'...
[09:26:03] gulp-debug: dev\Test1.html
buffer.js:179
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at DestroyableTransform._transform (C:\Source\GULPTestBed\GulpNewTest\node_modules\gulp-pre-proc\index.js:40:64)
    at DestroyableTransform.Transform._read (C:\Source\GULPTestBed\GulpNewTest\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Source\GULPTestBed\GulpNewTest\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Source\GULPTestBed\GulpNewTest\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (C:\Source\GULPTestBed\GulpNewTest\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (C:\Source\GULPTestBed\GulpNewTest\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\Source\GULPTestBed\GulpNewTest\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:115:13)
    at DestroyableTransform.emit (events.js:210:7)
```
I have zipped up the GulpNewTest dir where I did all this and you can download it here:
https://www.dropbox.com/s/sfmnx7zx70lum8q/GulpNewTest.zip?dl=0

Not sure what I have done wrong here, but I am able to replicate it using the above steps.

Thanks for your time,

codeowl1.

**Comment by anseki** [comment]
I see.
There is a file `Test1.html` that is not the file you showed.
Remove the `Test1.html` from `dev` directory, then the task should work without error.
That is, `Test1.html` has no 'BUNDLE_JS', then the error means that the tag couldn't be found.

BTW, you specified `'BUNDLE_JS'` as the `tag` option in the previous example but you specified `['BUNDLE_JS']` in the new example.
That must be a string. See document: https://github.com/anseki/pre-proc#picktag
It might work fine even if an Array that has single element was specified but that may make new problems.

**Comment by codeowl1** [comment]
@anseki,

Ah ok, I wasn't aware that you could only run it on files that had the tag, and if you ran it on any other files it would throw an error.  Is that a bug or behavior by design?  I would have thought it would just return the content or an empty string or something if it was not found.

Yes I tried the `['BUNDLE_JS']` array in an attempt to get it working.  Sorry I left that in.

So when I just run it on the Test2.html file with the tag in it, it runs without error, but how do I do anything with the result?  I tried commenting the following code:
```
        .pipe(through2.obj(function (chunk, enc, callback) {
            // The chunk comes through as a vinyl object https://github.com/wearefractal/vinyl
            console.log('we are here');
            console.log(chunk.toString(enc));
        }))
```
But the result when I run it the result is:
```
C:\Source\GULPTestBed\GulpNewTest
> gulp
[16:45:14] Using gulpfile C:\Source\GULPTestBed\GulpNewTest\gulpfile.js
[16:45:14] Starting 'test'...
[16:45:14] gulp-debug: dev\Test2.html
[16:45:14] gulp-debug: 1 item
[16:45:14] Finished 'test' after 32 ms
[16:45:14] Starting 'default'...
[16:45:14] Finished 'default' after 36 μs
```
So there is no evidence of the content in the tag being passed to the next pipe.
How can I access this?

Thanks again for your time,

codeowl1

**Comment by anseki** [comment]
The `pickTag` method is different from [`removeTag`](https://github.com/anseki/pre-proc#removetag) and [`replaceTag`](https://github.com/anseki/pre-proc#replacetag), it returns a found part of content. The `removeTag` and `replaceTag` methods return "content" always even if it was not changed.
That is, it matters whether the tag was found or not, it is very important. When a tag is empty (i.g. `<TAG></TAG>`), the `pickTag` method returns an empty string. When it could not find the tag, the method returns an `null`. These are correct behavior.

Typically, an user (like you) who uses the `pickTag` method want to do something with a found part of content. Therefore, the part should exist, and he or she know that the part exists in the content. The method should warn if the part doesn't exist. Otherwise, next task might do unexpected something.

Anyway, in future version, I might add a new option to ignore an error when a tag was not found.

So, if you want to do something with the piped content via through2, use `chunk.contents` instead of `chunk`.
For example:

```js
.pipe(through2.obj(function(chunk, enc) {
  console.log(chunk.contents.toString(enc));
}))
```

See: https://github.com/rvagg/through2

**Comment by codeowl1** [comment]
@anseki,

Thanks for the chunk.contents tip that is great, now I can get the content.

Yes it would be great if there was a better way to manage the files without the tags, as it is easyer to say /dir/*.html than maintain a list of which files have tags and which ones don't.  I guess I could use something like gulp-if to then make the decision weather to continue to the next pipe or not.
But the issue is at the moment, it just throws an error that I have no way of dealing with.

Anyway thanks for your help and taking the time to assist me.  Much appreciated mate ;-)

Regards,

codeowl1

**Comment by anseki** [comment]
I am glad that I could help you. :smile: 
So, was this issue solved? then, can you close this issue?

**Comment by codeowl1** [comment]
Yep will do.  If you add the option to ignore the error can you let me know please ;-)

Thanks again,

codeowl1

**Comment by anseki** [comment]
I updated the library.
Try the v2.0.1 and [`allowErrors`](https://github.com/anseki/gulp-pre-proc#picktag) option.

**Comment by codeowl1** [comment]
Oh brilliant work mate.  I will check it out!!
Thanks for following this up mate, much appreciated!!

**Comment by codeowl1** [comment]
@anseki  Just a quick follow up mate to let you know that the allowErrors option you added worked like a treat!!  Thanks again for your efforts!!

**Comment by anseki** [comment]
Thank you for your report! :smile:
